format_version: v1.0
type: UniqueComponent
attributes: {id: gfx_canvas}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: Canvas0FrameBufferAlloc}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: Auto}
  - type: Integer
    attributes: {id: Canvas0Height}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '480'}
  - type: Integer
    attributes: {id: Canvas0Width}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '800'}
  - type: Menu
    attributes: {id: Canvas1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Combo
    attributes: {id: Canvas1FrameBufferAlloc}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: Auto}
  - type: Integer
    attributes: {id: Canvas1Height}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '320'}
  - type: Integer
    attributes: {id: Canvas1Width}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '800'}
  - type: Menu
    attributes: {id: Canvas2}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Combo
    attributes: {id: Canvas2FrameBufferAlloc}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: Auto}
  - type: Integer
    attributes: {id: Canvas2Height}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '180'}
  - type: Integer
    attributes: {id: Canvas2Width}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '430'}
  - type: Integer
    attributes: {id: DefaultNumLayers}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_canvas, value: '3'}
  - type: String
    attributes: {id: DisplayDriverName}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_canvas, value: lcdcDisplayDriver}
  - type: Integer
    attributes: {id: NumCanvasObjects}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Menu
    attributes: {id: rtosMenu}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: gfx_display_driver}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: le_gfx_lcdc}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: le_gfx_driver_lcdc}
- type: ElementPosition
  attributes: {x: '635', y: '217', id: gfx_canvas}
