format_version: v1.0
type: UniqueComponent
attributes: {id: flexcom0}
children:
- type: Symbols
  children:
  - type: File
    attributes: {id: FLEXCOM0_COMMON_HEADER}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: dest}
        children:
        - {type: Value, value: /peripheral/flexcom/twi/}
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: plib_flexcom_twi_master.h}
      - type: String
        attributes: {id: project}
        children:
        - {type: Value, value: config/lcdc_rgba8888_mxt_9x60_wqvga/peripheral/flexcom/twi/}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: ../peripheral/flexcom_11268/templates/plib_flexcom_twi_master.h}
      - type: String
        attributes: {id: type}
        children:
        - {type: Value, value: HEADER}
  - type: File
    attributes: {id: FLEXCOM0_HEADER}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: dest}
        children:
        - {type: Value, value: /peripheral/flexcom/twi/}
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
      - type: Boolean
        attributes: {id: markup}
        children:
        - {type: Value, value: 'true'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: plib_flexcom0_twi.h}
      - type: String
        attributes: {id: project}
        children:
        - {type: Value, value: config/lcdc_rgba8888_mxt_9x60_wqvga/peripheral/flexcom/twi/}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: ../peripheral/flexcom_11268/templates/plib_flexcom_twi.h.ftl}
      - type: String
        attributes: {id: type}
        children:
        - {type: Value, value: HEADER}
  - type: File
    attributes: {id: FLEXCOM0_SOURCE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: dest}
        children:
        - {type: Value, value: /peripheral/flexcom/twi/}
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
      - type: Boolean
        attributes: {id: markup}
        children:
        - {type: Value, value: 'true'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: plib_flexcom0_twi.c}
      - type: String
        attributes: {id: project}
        children:
        - {type: Value, value: config/lcdc_rgba8888_mxt_9x60_wqvga/peripheral/flexcom/twi/}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: ../peripheral/flexcom_11268/templates/plib_flexcom_twi.c.ftl}
  - type: KeyValueSet
    attributes: {id: FLEXCOM_MODE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: flexcom0, value: '3'}
  - type: Integer
    attributes: {id: FLEXCOM_SPI_CSR_SCBR_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: flexcom0, value: '200'}
  - type: Integer
    attributes: {id: FLEXCOM_SPI_PERIPHERAL_CLOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: flexcom0, value: '200000000'}
  - type: File
    attributes: {id: FLEXCOM_SYS_DEF}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: markup}
        children:
        - {type: Value, value: 'true'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: core.LIST_SYSTEM_DEFINITIONS_H_INCLUDES}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: ../peripheral/flexcom_11268/templates/system/definitions.h.ftl}
      - type: String
        attributes: {id: type}
        children:
        - {type: Value, value: STRING}
  - type: File
    attributes: {id: FLEXCOM_SYS_INIT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: markup}
        children:
        - {type: Value, value: 'true'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: core.LIST_SYSTEM_INIT_C_SYS_INITIALIZE_PERIPHERALS}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: ../peripheral/flexcom_11268/templates/system/initialization.c.ftl}
      - type: String
        attributes: {id: type}
        children:
        - {type: Value, value: STRING}
  - type: Integer
    attributes: {id: FLEXCOM_TWI_CLK_SRC_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: flexcom0, value: '200000000'}
  - type: KeyValueSet
    attributes: {id: FLEXCOM_TWI_CWGR_BRSRCCLK}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: FLEXCOM_TWI_CWGR_CHDIV}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: flexcom0, value: '247'}
  - type: Integer
    attributes: {id: FLEXCOM_TWI_CWGR_CKDIV}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: flexcom0, value: '0'}
  - type: Integer
    attributes: {id: FLEXCOM_TWI_CWGR_CLDIV}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: flexcom0, value: '247'}
  - type: Combo
    attributes: {id: FLEXCOM_TWI_OPMODE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: FLEX_USART_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: flexcom0, value: '200000000'}
  - type: Integer
    attributes: {id: I2C_CLOCK_SPEED}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: String
    attributes: {id: RECEIVE_DATA_REGISTER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: flexcom0, value: '&(FLEXCOM0_REGS->FLEX_TWI_RHR)'}
  - type: String
    attributes: {id: TRANSMIT_DATA_REGISTER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: flexcom0, value: '&(FLEXCOM0_REGS->FLEX_TWI_THR)'}
  - type: Boolean
    attributes: {id: TWI_INTERRUPT_MODE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: FLEXCOM0_I2C}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drv_i2c_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: drv_i2c_I2C_dependency}
  - type: DirectCapability
    attributes: {id: FLEXCOM0_SPI}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: DirectCapability
    attributes: {id: FLEXCOM0_UART}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
- type: ElementPosition
  attributes: {x: '93', y: '149', id: flexcom0}
