format_version: v1.0
type: UniqueComponent
attributes: {id: plib_gfx2d}
children:
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: GFX2D}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: le_gfx_gfx2d}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: GFX2D}
- type: ElementPosition
  attributes: {x: '302', y: '440', id: plib_gfx2d}
