configName: lcdc_rgba8888_mxt_9x60_wvga
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: SAM9X60
projectName: ''
settings:
  PackageFilter: aerospace;audio;bsp;core;csp;gfx;gfx_apps_pic32mz_da;gfx_apps_pic32mz_da;gfx_apps_sam_9x60;gfx_apps_pic32mz_da;gfx_apps_pic32mz_da;gfx_apps_pic32mz_da;touch;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_RECENT
  DFPPath: .\dev_packs\Microchip\SAM9X60_DFP\1.4.40\atdf\SAM9X60.atdf
